import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  generateCiWorkflow,
  CI_TEMPLATE_KINDS,
  CI_TEMPLATE_LABELS,
  CI_TEMPLATE_PATHS,
  type CiTemplateKind,
} from '../src/commands/init-ci-templates.ts';

describe('CI_TEMPLATE_KINDS', () => {
  it('contains all expected kinds', () => {
    assert.deepEqual(
      [...CI_TEMPLATE_KINDS],
      ['basic', 'sarif', 'delta-pr-comment'],
    );
  });

  it('has labels for all kinds', () => {
    for (const kind of CI_TEMPLATE_KINDS) {
      assert.ok(CI_TEMPLATE_LABELS[kind], `Missing label for kind: ${kind}`);
    }
  });

  it('has paths for all kinds', () => {
    for (const kind of CI_TEMPLATE_KINDS) {
      assert.ok(CI_TEMPLATE_PATHS[kind], `Missing path for kind: ${kind}`);
    }
  });
});

describe('generateCiWorkflow', () => {
  it('generates valid YAML for basic template', () => {
    const yaml = generateCiWorkflow('basic');

    assert.ok(yaml.includes('name: shiori'));
    assert.ok(yaml.includes('on:'));
    assert.ok(yaml.includes('push:'));
    assert.ok(yaml.includes('pull_request:'));
    assert.ok(yaml.includes('shiori check'));
    assert.ok(yaml.includes('--fail-on expired,missing-in-registry'));
    assert.ok(yaml.includes('actions/checkout@v4'));
    assert.ok(yaml.includes('pnpm install --frozen-lockfile'));
  });

  it('generates valid YAML for sarif template', () => {
    const yaml = generateCiWorkflow('sarif');

    assert.ok(yaml.includes('name: shiori'));
    assert.ok(yaml.includes('security-events: write'));
    assert.ok(yaml.includes('shiori verify --format sarif'));
    assert.ok(yaml.includes('codeql-action/upload-sarif'));
    assert.ok(yaml.includes('category: shiori'));
  });

  it('generates valid YAML for delta-pr-comment template', () => {
    const yaml = generateCiWorkflow('delta-pr-comment');

    assert.ok(yaml.includes('name: shiori'));
    assert.ok(yaml.includes('save-baseline:'));
    assert.ok(yaml.includes('pr-delta:'));
    assert.ok(yaml.includes('pull-requests: write'));
    assert.ok(yaml.includes('shiori delta'));
    assert.ok(yaml.includes('--base-fallback-empty'));
    assert.ok(yaml.includes('--max-increase 0'));
    assert.ok(yaml.includes('peter-evans/create-or-update-comment@v4'));
    assert.ok(yaml.includes('shiori-delta'));
    assert.ok(yaml.includes('upload-artifact@v4'));
    assert.ok(yaml.includes('download-artifact@v4'));
  });

  it('includes generator comment for all templates', () => {
    for (const kind of CI_TEMPLATE_KINDS) {
      const yaml = generateCiWorkflow(kind);
      assert.ok(
        yaml.includes(`Generated by: shiori init --ci ${kind}`),
        `Missing generator comment for kind: ${kind}`,
      );
    }
  });

  it('includes Node.js 22 for all templates', () => {
    for (const kind of CI_TEMPLATE_KINDS) {
      const yaml = generateCiWorkflow(kind);
      assert.ok(
        yaml.includes("node-version: '22'"),
        `Missing Node.js 22 for kind: ${kind}`,
      );
    }
  });

  it('includes pnpm setup for all templates', () => {
    for (const kind of CI_TEMPLATE_KINDS) {
      const yaml = generateCiWorkflow(kind);
      assert.ok(
        yaml.includes('pnpm/action-setup@v4'),
        `Missing pnpm setup for kind: ${kind}`,
      );
    }
  });

  it('all templates output non-empty strings', () => {
    for (const kind of CI_TEMPLATE_KINDS) {
      const yaml = generateCiWorkflow(kind);
      assert.ok(yaml.length > 0, `Empty output for kind: ${kind}`);
    }
  });
});
