/**
 * GitHub Actions workflow templates for shiori CI integration.
 *
 * Each template is a pure function returning YAML string content.
 * Template selection is driven by CiTemplateKind (defined in core/types.ts).
 */

import type { CiTemplateKind } from '../core/types.ts';

// Re-export for backward compatibility
export type { CiTemplateKind } from '../core/types.ts';

/** All valid CI template kinds (single source of truth) */
export const CI_TEMPLATE_KINDS: readonly CiTemplateKind[] = [
  'basic',
  'sarif',
  'delta-pr-comment',
  'checks-gate',
  'badge',
  'badge-gist',
];

/** Human-readable label for each CI template kind */
export const CI_TEMPLATE_LABELS: Record<CiTemplateKind, string> = {
  basic: 'Basic check (scan + verify on push/PR)',
  sarif: 'SARIF upload (scan + verify + GitHub Code Scanning)',
  'delta-pr-comment': 'Delta PR comment (baseline + PR diff + comment)',
  'checks-gate': 'Checks gate (PR status check for merge blocking)',
  badge: 'Badge (governance score badge via GitHub Actions Artifacts)',
  'badge-gist':
    'Badge + Gist (governance score badge uploaded to GitHub Gist for stable URL)',
};

/** Output file path for each template kind */
export const CI_TEMPLATE_PATHS: Record<CiTemplateKind, string> = {
  basic: '.github/workflows/shiori.yml',
  sarif: '.github/workflows/shiori.yml',
  'delta-pr-comment': '.github/workflows/shiori.yml',
  'checks-gate': '.github/workflows/shiori.yml',
  badge: '.github/workflows/shiori-badge.yml',
  'badge-gist': '.github/workflows/shiori-badge.yml',
};

/**
 * Generate a CI workflow YAML for the given template kind.
 * Pure function — no I/O.
 */
export function generateCiWorkflow(kind: CiTemplateKind): string {
  switch (kind) {
    case 'basic':
      return BASIC_TEMPLATE;
    case 'sarif':
      return SARIF_TEMPLATE;
    case 'delta-pr-comment':
      return DELTA_PR_COMMENT_TEMPLATE;
    case 'checks-gate':
      return CHECKS_GATE_TEMPLATE;
    case 'badge':
      return BADGE_TEMPLATE;
    case 'badge-gist':
      return BADGE_GIST_TEMPLATE;
  }
}

// ── Templates ────────────────────────────────────────────────

const BASIC_TEMPLATE = `# Generated by: shiori init --ci basic
# Runs shiori check on every push and pull request.
# Customize --fail-on and --warn-on to match your governance policy.

name: shiori

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: shiori check
        run: pnpm shiori check --fail-on expired,missing-in-registry
`;

const SARIF_TEMPLATE = `# Generated by: shiori init --ci sarif
# Runs shiori verify with SARIF output for GitHub Code Scanning integration.
# Results appear in the Security → Code scanning alerts tab.

name: shiori

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: shiori check
        run: pnpm shiori check --fail-on expired,missing-in-registry
        continue-on-error: true

      - name: Generate SARIF
        run: pnpm shiori verify --format sarif --output .tmp/shiori.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .tmp/shiori.sarif
          category: shiori
`;

const DELTA_PR_COMMENT_TEMPLATE = `# Generated by: shiori init --ci delta-pr-comment
# Saves a baseline scan on main, computes annotation delta on PRs,
# and posts the diff as a PR comment.
# See: docs/recipes/github-actions-delta-pr-comment.md

name: shiori

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Save baseline scan on push to main
  save-baseline:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm shiori scan --output .tmp/shiori-base-scan.json
      - uses: actions/upload-artifact@v4
        with:
          name: shiori-base-scan
          path: .tmp/shiori-base-scan.json
          overwrite: true

  # Compute delta on PR and post comment
  pr-delta:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      # download-artifact@v4 cannot retrieve artifacts across workflow runs
      # (push and pull_request run as separate runs even in the same workflow).
      # Use GitHub API via github-script to fetch the baseline from the latest
      # successful push run.
      - name: Download baseline scan artifact
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const workflows = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            const baselineWorkflow = workflows.data.workflows.find(
              w => w.name === 'shiori'
            );
            if (!baselineWorkflow) return;

            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: baselineWorkflow.id,
              branch: 'main',
              status: 'success',
              per_page: 1,
            });
            if (runs.data.workflow_runs.length === 0) return;

            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runs.data.workflow_runs[0].id,
            });
            const artifact = artifacts.data.artifacts.find(
              a => a.name === 'shiori-base-scan'
            );
            if (!artifact) return;

            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifact.id,
              archive_format: 'zip',
            });
            fs.mkdirSync('.tmp', { recursive: true });
            fs.writeFileSync('.tmp/shiori-base-scan.zip', Buffer.from(download.data));
            require('child_process').execSync('unzip -o .tmp/shiori-base-scan.zip -d .tmp/');
        continue-on-error: true

      - name: Scan (PR head)
        run: pnpm shiori scan --output .tmp/shiori-head-scan.json

      - name: Compute delta
        id: delta
        run: |
          pnpm shiori delta \\
            --base .tmp/shiori-base-scan.json \\
            --head .tmp/shiori-head-scan.json \\
            --format markdown \\
            --base-fallback-empty \\
            --max-increase 0 \\
            --output .tmp/shiori-delta.md
        continue-on-error: true

      # Append onboarding section for developers unfamiliar with shiori.
      # Remove this step once your team is onboarded.
      # See: docs/recipes/pr-onboarding-snippet.md
      - name: Append onboarding section
        run: |
          cat >> .tmp/shiori-delta.md << 'ONBOARDING'

          ---

          <details>
          <summary>💡 shiori について</summary>

          **shiori** はソースコード中の lint disable コメントや技術的判断を追跡・管理するガバナンスツールです。

          このコメントは \`shiori delta\` によって自動投稿されています。

          ### クイックスタート

          \`\`\`bash
          # インストール
          pnpm add -D shiori

          # プロジェクト初期化（レジストリ + CI テンプレート生成）
          pnpm shiori init

          # lint disable の候補を検出して追跡開始
          pnpm shiori candidates
          pnpm shiori adopt

          # レジストリとの整合性を検証
          pnpm shiori check
          \`\`\`

          📖 詳細: \`pnpm shiori docs\`

          </details>
          ONBOARDING

      - name: Post delta as PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: \${{ github.event.pull_request.number }}
          body-path: .tmp/shiori-delta.md
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- shiori-delta -->'

      - name: Fail if annotation count increased
        if: steps.delta.outcome == 'failure'
        run: exit 1
`;

const CHECKS_GATE_TEMPLATE = `# Generated by: shiori init --ci checks-gate
# Runs shiori check as a PR status check for merge blocking.
# Configure branch protection rules to require this check.
# See: docs/recipes/github-checks-gate.md

name: shiori governance

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # shiori check runs scan + verify in one step.
      # Exit code 1 on --fail-on matches → GitHub marks the check as failed.
      - name: shiori check
        run: pnpm shiori check --fail-on expired,missing-in-registry
`;

const BADGE_TEMPLATE = `# Generated by: shiori init --ci badge
# Generates a governance score badge JSON (shields.io endpoint) and uploads it as a GitHub Actions Artifact.
# The badge URL uses the nightly.link service for public access:
#   https://nightly.link/<owner>/<repo>/workflows/shiori-badge/main/shiori-badge.zip
#
# To use with Gist (optional):
#   1. Create a Gist and note the Gist ID
#   2. Create a PAT with gist scope and add as GIST_TOKEN secret
#   3. Uncomment the "Upload badge to Gist" step below
#
# See: docs/recipes/governance-badge.md

name: shiori badge

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate badge
        run: pnpm shiori report --format badge --output .tmp/shiori-badge.json

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: shiori-badge
          path: .tmp/shiori-badge.json
          overwrite: true

      # Uncomment to upload badge to a GitHub Gist for stable URL access.
      # Requires: GIST_TOKEN secret (PAT with gist scope) and GIST_ID variable.
      #
      # - name: Upload badge to Gist
      #   uses: exuanbo/actions-deploy-gist@v1
      #   with:
      #     token: \${{ secrets.GIST_TOKEN }}
      #     gist_id: \${{ vars.GIST_ID }}
      #     file_path: .tmp/shiori-badge.json
      #     file_type: text
`;

const BADGE_GIST_TEMPLATE = `# Generated by: shiori init --ci badge-gist
# Generates a governance score badge JSON (shields.io endpoint), uploads it as
# a GitHub Actions Artifact AND to a GitHub Gist for a stable badge URL.
#
# Prerequisites:
#   1. Create a GitHub Gist and note the Gist ID
#   2. Create a PAT with gist scope and add it as GIST_TOKEN repository secret
#   3. Add the Gist ID as GIST_ID repository variable
#
# Badge URL (Gist):
#   https://img.shields.io/endpoint?url=https://gist.githubusercontent.com/<owner>/<gist_id>/raw/shiori-badge.json
#
# See: docs/recipes/governance-badge.md

name: shiori badge

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate badge
        run: pnpm shiori report --format badge --output .tmp/shiori-badge.json

      - name: Upload badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: shiori-badge
          path: .tmp/shiori-badge.json
          overwrite: true

      - name: Upload badge to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: \${{ secrets.GIST_TOKEN }}
          gist_id: \${{ vars.GIST_ID }}
          file_path: .tmp/shiori-badge.json
          file_type: text
`;
