/**
 * GitHub Actions workflow templates for shiori CI integration.
 *
 * Each template is a pure function returning YAML string content.
 * Template selection is driven by CiTemplateKind.
 */

/** Available CI template kinds */
export type CiTemplateKind = 'basic' | 'sarif' | 'delta-pr-comment';

/** All valid CI template kinds (single source of truth) */
export const CI_TEMPLATE_KINDS: readonly CiTemplateKind[] = [
  'basic',
  'sarif',
  'delta-pr-comment',
];

/** Human-readable label for each CI template kind */
export const CI_TEMPLATE_LABELS: Record<CiTemplateKind, string> = {
  basic: 'Basic check (scan + verify on push/PR)',
  sarif: 'SARIF upload (scan + verify + GitHub Code Scanning)',
  'delta-pr-comment': 'Delta PR comment (baseline + PR diff + comment)',
};

/** Output file path for each template kind */
export const CI_TEMPLATE_PATHS: Record<CiTemplateKind, string> = {
  basic: '.github/workflows/shiori.yml',
  sarif: '.github/workflows/shiori.yml',
  'delta-pr-comment': '.github/workflows/shiori.yml',
};

/**
 * Generate a CI workflow YAML for the given template kind.
 * Pure function — no I/O.
 */
export function generateCiWorkflow(kind: CiTemplateKind): string {
  switch (kind) {
    case 'basic':
      return BASIC_TEMPLATE;
    case 'sarif':
      return SARIF_TEMPLATE;
    case 'delta-pr-comment':
      return DELTA_PR_COMMENT_TEMPLATE;
  }
}

// ── Templates ────────────────────────────────────────────────

const BASIC_TEMPLATE = `# Generated by: shiori init --ci basic
# Runs shiori check on every push and pull request.
# Customize --fail-on and --warn-on to match your governance policy.

name: shiori

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: shiori check
        run: pnpm shiori check --fail-on expired,missing-in-registry
`;

const SARIF_TEMPLATE = `# Generated by: shiori init --ci sarif
# Runs shiori verify with SARIF output for GitHub Code Scanning integration.
# Results appear in the Security → Code scanning alerts tab.

name: shiori

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: shiori check
        run: pnpm shiori check --fail-on expired,missing-in-registry
        continue-on-error: true

      - name: Generate SARIF
        run: pnpm shiori verify --format sarif --output .tmp/shiori.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: .tmp/shiori.sarif
          category: shiori
`;

const DELTA_PR_COMMENT_TEMPLATE = `# Generated by: shiori init --ci delta-pr-comment
# Saves a baseline scan on main, computes annotation delta on PRs,
# and posts the diff as a PR comment.
# See: docs/recipes/github-actions-delta-pr-comment.md

name: shiori

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Save baseline scan on push to main
  save-baseline:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm shiori scan --output .tmp/shiori-base-scan.json
      - uses: actions/upload-artifact@v4
        with:
          name: shiori-base-scan
          path: .tmp/shiori-base-scan.json
          overwrite: true

  # Compute delta on PR and post comment
  pr-delta:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile

      - uses: actions/download-artifact@v4
        with:
          name: shiori-base-scan
          path: .tmp/
        continue-on-error: true

      - name: Scan (PR head)
        run: pnpm shiori scan --output .tmp/shiori-head-scan.json

      - name: Compute delta
        id: delta
        run: |
          pnpm shiori delta \\
            --base .tmp/shiori-base-scan.json \\
            --head .tmp/shiori-head-scan.json \\
            --format markdown \\
            --base-fallback-empty \\
            --max-increase 0 \\
            --output .tmp/shiori-delta.md
        continue-on-error: true

      - name: Post delta as PR comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: \${{ github.event.pull_request.number }}
          body-path: .tmp/shiori-delta.md
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- shiori-delta -->'

      - name: Fail if annotation count increased
        if: steps.delta.outcome == 'failure'
        run: exit 1
`;
