/**
 * Starter templates for `shiori init --starter`.
 *
 * Each template generates sample source files and matching registry
 * entries so that `shiori check` succeeds immediately after init.
 * This gives new users a working example to explore.
 */

import type { Registry } from '../core/types.ts';
import type { CandidatePatternConfig } from '../core/providers/AnnotationProvider.ts';

/** Available starter template kinds */
export type StarterKind = 'eslint' | 'stylelint' | 'typescript' | 'minimal';

/** All valid starter kinds (single source of truth) */
export const STARTER_KINDS: readonly StarterKind[] = [
  'eslint',
  'stylelint',
  'typescript',
  'minimal',
];

/** Human-readable label for each starter kind */
export const STARTER_LABELS: Record<StarterKind, string> = {
  eslint: 'ESLint disable example (JavaScript/TypeScript)',
  stylelint: 'Stylelint disable example (CSS/SCSS)',
  typescript: 'TypeScript directive example (@ts-expect-error)',
  minimal: 'Minimal standalone shiori annotation',
};

/** A generated sample file */
export interface StarterFile {
  /** Relative path from project root */
  path: string;
  /** File content */
  content: string;
}

/** Result of generating a starter template */
export interface StarterResult {
  /** Sample source files to create */
  files: StarterFile[];
  /** Registry entries to merge */
  registry: Registry;
  /** Scan patterns needed to pick up the sample files */
  scanPatterns: string[];
  /** Additional candidate patterns required to detect annotations in sample files */
  candidatePatterns?: CandidatePatternConfig;
}

/**
 * Generate starter template content for the given kind.
 * Pure function — no I/O.
 */
export function generateStarter(kind: StarterKind): StarterResult {
  switch (kind) {
    case 'eslint':
      return generateEslintStarter();
    case 'stylelint':
      return generateStylelintStarter();
    case 'typescript':
      return generateTypescriptStarter();
    case 'minimal':
      return generateMinimalStarter();
  }
}

// ── Template generators ──────────────────────────────────────

function generateEslintStarter(): StarterResult {
  return {
    files: [
      {
        path: 'examples/shiori-sample.ts',
        content: `// This file demonstrates how shiori tracks ESLint disable comments.
// Each disabled rule is recorded in the registry with a reason and owner.

// eslint-disable-next-line no-console -- shiori: EXAMPLE-001 reason=demo
console.log('Hello from shiori starter');
`,
      },
    ],
    registry: {
      'EXAMPLE-001': {
        reason: 'Starter example: console.log for demonstration purposes',
        target: 'examples/shiori-sample.ts',
        expires: undefined,
        ticket: undefined,
        owner: 'team',
        notes:
          'Generated by shiori init --starter eslint. Safe to modify or remove.',
        kind: 'example',
      },
    },
    scanPatterns: ['examples/**/*.ts'],
  };
}

function generateStylelintStarter(): StarterResult {
  return {
    files: [
      {
        path: 'examples/shiori-sample.css',
        content: `/* This file demonstrates how shiori tracks Stylelint disable comments. */

/* stylelint-disable-next-line color-named -- shiori: EXAMPLE-001 reason=demo */
.banner { color: red; }
`,
      },
    ],
    registry: {
      'EXAMPLE-001': {
        reason: 'Starter example: named color for demonstration purposes',
        target: 'examples/shiori-sample.css',
        expires: undefined,
        ticket: undefined,
        owner: 'team',
        notes:
          'Generated by shiori init --starter stylelint. Safe to modify or remove.',
        kind: 'example',
      },
    },
    scanPatterns: ['examples/**/*.css'],
  };
}

function generateTypescriptStarter(): StarterResult {
  return {
    files: [
      {
        path: 'examples/shiori-sample.ts',
        content: `// This file demonstrates how shiori tracks TypeScript directive comments.

// @ts-expect-error -- shiori: EXAMPLE-001 reason=demo
const value: number = 'not a number';
void value;
`,
      },
    ],
    registry: {
      'EXAMPLE-001': {
        reason: 'Starter example: type assertion override for demonstration',
        target: 'examples/shiori-sample.ts',
        expires: undefined,
        ticket: undefined,
        owner: 'team',
        notes:
          'Generated by shiori init --starter typescript. Safe to modify or remove.',
        kind: 'example',
      },
    },
    scanPatterns: ['examples/**/*.ts'],
    candidatePatterns: { typescript: true },
  };
}

function generateMinimalStarter(): StarterResult {
  return {
    files: [
      {
        path: 'examples/shiori-sample.ts',
        content: `// This file demonstrates a standalone shiori annotation.
// No lint tool required — shiori tracks any comment with the shiori: marker.

// shiori: EXAMPLE-001 reason=demo
const GREETING = 'Hello from shiori';
export { GREETING };
`,
      },
    ],
    registry: {
      'EXAMPLE-001': {
        reason: 'Starter example: standalone annotation for demonstration',
        target: 'examples/shiori-sample.ts',
        expires: undefined,
        ticket: undefined,
        owner: 'team',
        notes:
          'Generated by shiori init --starter minimal. Safe to modify or remove.',
        kind: 'example',
      },
    },
    scanPatterns: ['examples/**/*.ts'],
  };
}
